DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
	`ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`username` VARCHAR(12) NOT NULL,
	`password` CHAR(255) NOT NULL,
	`registered` DATETIME NOT NULL DEFAULT current_timestamp(),
	`moderator` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
	`banned` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (`ID`),
	UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=100 DEFAULT CHARSET=latin1;

LOCK TABLES `users` WRITE;
INSERT INTO `users` (`ID`, `username`, `password`) VALUES (100, 'Zaseth', '43244635c14605fdbe23fa89b5cf12bd14a14bfb9420f66788dd6914a31d8c7b');
UNLOCK TABLES;